```c++
#include <iostream>
#include <cmath>
#include <exception>
#include <stdexcept>
#include <string>
using namespace std;

double hmean(double a, double b);
double gmean(double a, double b);
class hlogic_error :public logic_error {
public:
	explicit hlogic_error(const string& what_arg) :logic_error(what_arg) {};
};
class glogic_error :public logic_error {
public:
	explicit glogic_error(const string& what_arg) :logic_error(what_arg) {};
};


int main(void)
{

	double x, y, z;

	cout << "Enter two numbers: ";
	while (cin >> x >> y)
	{
		try {
			z = hmean(x, y);
			cout << "Harmonic mean of " << x << " and " << y << " is " << z << endl;
			cout << "Geometric mean of " << x << " and " << y << " is " << gmean(x, y) << endl;
			cout << "Enter next set of numbers <q to quit>: ";
		}
		catch (const hlogic_error hle) {
			cerr << "Caught: " << hle.what() << endl;
			continue;
		}
		catch (const glogic_error gle) {
			cerr << "Caught: " << gle.what() << endl;
			break;
		}
	}
	cout << "Bye!\n";
	return 0;
}
double hmean(double a, double b)
{
	if (a == -b)throw hlogic_error("Try again.\n");
	return 2.0 * a * b / (a + b);
}
double gmean(double a, double b)
{
	if (a < 0 || b < 0)throw glogic_error("Values used: " + to_string(a) + ", " + to_string(b) + "\nSorry, you don't get to play any more.\n");
	return std::sqrt(a * b);
}
```

